-- DEPRECADO / NO EJECUTAR EN PRODUCCIÓN.
--
-- Este proyecto usa Prisma como única fuente de verdad del esquema y las migraciones.
-- El antiguo init.sql contenía un esquema obsoleto, sedes antiguas y cuentas administrativas
-- predecibles; se conserva este archivo únicamente para evitar que documentación o automatizaciones
-- antiguas fallen al buscarlo, pero ya no crea ni modifica ninguna tabla o usuario.
--
-- Flujo soportado para preparar una base de datos nueva:
--   cd backend
--   npm ci
--   npx prisma generate
--   npx prisma migrate deploy
--   npm run seed
--
-- Antes del seed configure ADMIN_BOOTSTRAP_NAME, ADMIN_BOOTSTRAP_EMAIL y una
-- ADMIN_BOOTSTRAP_PASSWORD aleatoria y fuerte. El bootstrap debe cambiar la contraseña y
-- configurar MFA en el primer ingreso. Después retire esas variables del entorno cuando sea posible.
--
-- Nunca cree administradores mediante SQL manual ni reutilice contraseñas compartidas.
